### ISSUE TITLE
Can someone `rewrite it with rust`?

### ISSUE THREAD

**Issue by olivertzeng** [charmbracelet/lipgloss#123]
[`Rewrite it with Rust`](https://discord.com/channels/601130461678272522/988303282931912704/1025006163043029073)

**Comment by muesli** [comment]
I'm sure everything we do here could be re-implemented in a variety of other languages, like Rust. Please keep the tickets related to the current code-base and project tho, otherwise it's quickly becoming unmaintainable. The Discord link seems broken.

**Comment by olivertzeng** [comment]
ok sorry

**Comment by olivertzeng** [comment]
oh its the nushell discord server
![截圖 2022-09-29 下午8 53 57](https://user-images.githubusercontent.com/86348833/193036698-7266d638-752e-46ff-b4de-4abb8ef92b5b.png)

**Comment by olivertzeng** [comment]
@muesli

**Comment by muesli** [comment]
> ok sorry

No worries, I hope you understand. Thanks for resolving the Discord mystery link, I appreciate it!

**Comment by olivertzeng** [comment]
@muesli I think I mis-expressed my meaning. I meant: can this program be programmed with rust? (I dont mean to rewrite this with rust)
