### ISSUE TITLE
Revision cannot be found

### ISSUE THREAD

**Issue by jonrosner** [charmbracelet/lipgloss#149]
While installing another library I got the error

```
/.../pkg/mod/github.com/charmbracelet/lipgloss@v0.6.1-0.20221011104340-92c8fa0a572b/align.go:7:2: github.com/muesli/termenv@v0.12.1-0.20220901123159-d729275e0977: invalid version: unknown revision d729275e0977
```

was there a deleted revision? If yes, it possible to recreate it so other libraries do not fail to install?

**Comment by muesli** [comment]
I can't reproduce this. Revision `92c8fa0a572b` of lipgloss depends on:

```
github.com/muesli/termenv v0.11.1-0.20220204035834-5ac8409525e0
```

**Comment by jonrosner** [comment]
Looks like this is caused by the `goreleaser` build being broken. I will close this and open an issue in goreleaser
