### ISSUE TITLE
feat: table renderer

### ISSUE THREAD

**Issue by meowgorithm** [charmbracelet/lipgloss#162]
The rendering portion of [the table bubble](https://github.com/charmbracelet/bubbles#table) should live in this library so we can also support static table rendering.

Related: https://github.com/charmbracelet/bubbletea/issues/618

**Comment by MichaelMure** [comment]
More generally, don't we want the equivalent of `JoinHorizontal`/`JoinVertical`, but able to do a wider range of CSS Flexbox capabilities (grow, shrink, wrap ...)? With that, rendering a table would be trivial.

**Comment by caarlos0** [comment]
I think this is done, no? `table` is a lipgloss package now 🤔
