### ISSUE TITLE
is boder bug?

### ISSUE THREAD

**Issue by njfanxun** [charmbracelet/lipgloss#186]
```go
var style = lipgloss.NewStyle().
		Border(lipgloss.NormalBorder(), true, true, true, true).
		BorderForeground(lipgloss.Color("63"))
fmt.Println(style.Render("Hello, kitty"))
```
output is
![image](https://user-images.githubusercontent.com/1555047/227134941-1b76c230-17fc-4c3f-82c6-e0dbc596f6f7.png)
i think the string width calc has some problem

**Comment by meowgorithm** [comment]
Hi! This is due to your encoding: see https://github.com/charmbracelet/lipgloss/issues/30 and https://github.com/charmbracelet/lipgloss/issues/40.

**Comment by bashbunni** [comment]
We should document this in our FAQ
