### ISSUE TITLE
Example to toggle full screen?

### ISSUE THREAD

**Issue by vsoch** [charmbracelet/lipgloss#190]
Hi! I have a keymap that I want to indicate full screen, and my code under the view Update() looks like:

```go
	case key.Matches(msg, m.keyMap.fullscreen):
	var cmd tea.Cmd
	if m.fullscreen {
		cmd = tea.ExitAltScreen
	} else {
  	 	cmd = tea.EnterAltScreen
	}
	m.fullscreen = !m.fullscreen
	return cmd
}
```
It seems to show some side content of the vscode terminal, but I don't see it fully minimize like in the example here: https://github.com/charmbracelet/bubbletea/tree/master/examples/altscreen-toggle

Is there a special way that Lipgloss can work with the altscreen provided by tea?

**Comment by bashbunni** [comment]
Hi @vsoch could you please show us what they current behaviour is, and what you're hoping to achieve? I'm not sure I understand what you mean by "minimize" in this case

**Comment by vsoch** [comment]
This example https://github.com/charmbracelet/bubbletea/tree/master/examples/altscreen-toggle is the behavior I want. And this is what I'm getting - when I press "t" the screen sort of jumps and I can see dots on the left side, and the scrollbar on the right, but it doesn't actually minimize like the example I linked above.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/814322/229886530-f6bf259d-fa71-4469-9e67-ff62844fb289.gif)

**Comment by bashbunni** [comment]
@vsoch interesting... I *think* I know what you mean. Does this occur in your regular terminal as well? (as opposed to the terminal built-in to VS Code)

**Comment by vsoch** [comment]
In my regular terminal it doesn't show even the side bits (the dots or the sidebar) it looks like nothing is happening! The example I linked above (just tested) works in both terminals. So I don't think it's a VSCode thing.

**Comment by bashbunni** [comment]
Hey @vsoch are you also returning model in this code block? You'll either need `m` to be a pointer to your model or return `m` after making your changes. The `tea.Model` interface doesn't use pointers and instead returns the model after each `Update`

```go
	case key.Matches(msg, m.keyMap.fullscreen):
	var cmd tea.Cmd
	if m.fullscreen {
		cmd = tea.ExitAltScreen
	} else {
  	 	cmd = tea.EnterAltScreen
	}
	m.fullscreen = !m.fullscreen // are you returning this model?
	return cmd
}
```

**Comment by bashbunni** [comment]
Hey @vsoch is this still an issue for you?

**Comment by vsoch** [comment]
I've stopped working on it, so happy to close. Thanks for checking in!
