### ISSUE TITLE
random output of ANSI escape sequences with 0.7.1

### ISSUE THREAD

**Issue by benleb** [charmbracelet/lipgloss#191]
hey 👋 great lib guys, i love it! 🫶

Unfortunately  I encountered my first issue with it now :D You can see it in the screen (from kitty on current macos (intel, no m1/2))
![image](https://user-images.githubusercontent.com/512997/229927058-18721002-478b-488e-abbb-ffeab3a40acd.png)

With 0.6.0 everything works fine since weeks and on multiple devices/OS. So I am pretty sure it has something todo with the upgrade to 0.7.1 :) I unfortunately cannot see a "pattern" or a "trigger" that causes it, it seems completely random to me.

Its also reproducible, it happens every few sec/min as soon as lipgloss is on 0.7.1 :/

Has anybody a hint whats could be the problem? Not even sure if its a bug? Or just wrong usage? 🤷‍♀️ 
Brought this up in the discord without a clue to solve it yet 🕵️

**Comment by muesli** [comment]
This is lipgloss querying the terminal for its color support. It should only ever happen once on startup, and you're obviously not supposed to see it. How do you reproduce that?

**Comment by hopefulTex** [comment]
Was this a problem with version > 6.0, or just 7.1?
Do you have a repo with at least your `View`?
Does this happen on a fresh Kitty install?

**Comment by benleb** [comment]
sorry for the delay, easter time 🐰

uargh sorry, I did not mean "reproducible" 😅🤦‍♀️ I just can see if it works or not quite fast (no hour-long wait times to see if a fix works for example). I unfortunately don't know which function call triggers this.

>This is lipgloss querying the terminal for its color support.

ah nice thanks! which commands trigger this "color support check"? 


> Was this a problem with version > 6.0, or just 7.1?

also with 0.7.0

> Do you have a repo with at least your View?

hm do you have a bubbletea app in mind? it is not yet on that level unfortunately 😅 Just plain lipgloss. The code is currently not in a public repo, but I work on that (hours or days). But do not expect a proper structured go project or something like this... It's a tool that was/is hacked together by me and other people with very less go experience and no time 😅

> Does this happen on a fresh Kitty install?

Hm I did not test it explicitly, but I use kitty exclusively for this tool and just adjusted the font and font size in the config, everything else is default.

**Comment by benleb** [comment]
hey, thanks & sorry 🙄 your hint with the concurrent print calls may have pointed me in the right direction! That was indeed the case but after fixing it I found out it had nothing todo with the issue 😅 but lead me to something else and I might found the file causing the issue.... Gimme some more hours to test and narrow it down, I will get back to you with more details then 👍

**Comment by lemoony** [comment]
I can affirm the findings of @Jcambass. I have to downgrade to lipgloss v0.6.0 for now - along with bubbles which depend on v0.7.1.

**Comment by aymanbagabas** [comment]
Could you try out the new release and see if the issue still exists? https://github.com/charmbracelet/lipgloss/releases/tag/v0.8.0
