### ISSUE TITLE
TopRight and BottomRight border not showing when rendering an empty string and no left border

### ISSUE THREAD

**Issue by UnseenBook** [charmbracelet/lipgloss#214]
**Describe the bug**
Rendering an empty string with a border style and no left border, it doesn't render the TopRight and BottomRight corders.
Using DoubleBorder you would expect it to look like this:
```
╗
║
╝
```
But it ends up looking like this:
```

║

```

**Setup**
Not applicable, but here you go:
 - OS: ArchLinux
 - Shell: Bash
 - Terminal Emulator: tilix
 - Locale: en_US.UTF-8

**To Reproduce**
Run the following:
```Go
package main

import (
	"fmt"
	"github.com/charmbracelet/lipgloss"
)

func main() {
	noLeftStyle := lipgloss.NewStyle().
		Border(lipgloss.DoubleBorder()).
		BorderLeft(false)
	fmt.Println(noLeftStyle.Render(""))
}
```

**Solution**
I submitted a PR to fix this: #211 
Horizontal edges aren't rendered when width is 0, which doesn't take corners into consideration.
When the left border is enabled, `width` is incremented once, so with a left border enabled, `width` is never 0.

**Comment by meowgorithm** [comment]
Hi! We still need to review it but #211 should solve this.

**Comment by zhangddjs** [comment]
Also I meet a bug here, while I set top border false, all border went missing.

![image](https://github.com/charmbracelet/lipgloss/assets/30108045/cbe09268-3bbd-4f34-9eb1-73a0d3a26de1)
