### ISSUE TITLE
 Overlap views

### ISSUE THREAD

**Issue by gczgcz2015** [charmbracelet/lipgloss#238]
can i create overlap views like lazygit
![image](https://github.com/charmbracelet/lipgloss/assets/15188637/68e70b1e-e594-455d-b2f4-6f0347104c57)

**Comment by caozhuozi** [comment]
Any updates on this...

**Comment by StephGD** [comment]
Hello ! Try this : https://github.com/mrusme/neonmodem/commit/cd7b173cc7b9db8224d4cf944c6da5391516767d
It's a little bit tricky but it works fine.

**Comment by gczgcz2015** [comment]
@StephGD thx i will try it.
#102 discuss this feature closed this issue
