### ISSUE TITLE
Table: truncation breaks ANSI styling

### ISSUE THREAD

**Issue by meowgorithm** [charmbracelet/lipgloss#266]
It appears that when truncation occurs on cell data with ansi styling present the ANSI reset sequence is truncated, resulting in the styling from the cell bleeding onto subsequent rows:

In other words it appears that something like the following is happening:

```go
"\x1b[7m " + "Milk!" + "\x1b[0m" // before; ends in ANSI reset
"\x1b[7m " + "Mi…" // post-truncation; ANSI reset missing
```

***

The following code will reproduce the issue:

```go
package main

import (
	"fmt"

	"github.com/charmbracelet/lipgloss"
	"github.com/charmbracelet/lipgloss/table"
)

func main() {
	s := lipgloss.NewStyle().Foreground(lipgloss.Color("240")).Render

	t := table.New()
	t.Row("Bubble Tea", s("Milky"))
	t.Row("Milk Tea", s("Also milky"))
	t.Row("Actual milk", s("Milky as well"))
	fmt.Println(t.Render())
}
```

Output:

<img width="590" src="https://github.com/charmbracelet/lipgloss/assets/25087/61fd8c62-c5b4-4d91-8d82-93a1052e4203">

**Comment by maaslalani** [comment]
We should be using `StyleFunc` to style these cells.

```go
func main() {
	s := lipgloss.NewStyle().Foreground(lipgloss.Color("240"))

	t := table.New()
	t.Row("Bubble Tea", "Milky")
	t.Row("Milk Tea", "Also milky")
	t.Row("Actual milk", "Milky as well")
        t.StyleFunc(func (row, col int) lipgloss.Style {
            if col == 1 {
                return s
            }
            return lipgloss.NewStyle()
        })
	fmt.Println(t.Render())
}
```

**Comment by meowgorithm** [comment]
Aha: @maaslalani pointed out that this is actually fixed on `master`. Sounds like it's time for a release then.

**Comment by maaslalani** [comment]
This was solved by the awesome @mikelorant!

https://github.com/charmbracelet/lipgloss/commit/de4601232b791a1397d6c645904b001a311a5693
