### ISSUE TITLE
Weird behaviour when using lipgloss in a test

### ISSUE THREAD

**Issue by LaBatata101** [charmbracelet/lipgloss#287]
**Describe the bug**
I have a test that prints a colored output, but when executing this test outside of the folder containing the test, the colored output is not shown. If I execute the same test, but this time inside of the folder containing the test, the colored output is shown. This also affects any other styles you can apply to a text, not only colors.

**Setup**
 - OS: Manjaro KDE
 - Shell: zsh
 - Terminal Emulator: kitty

**To Reproduce**
1. Create a folder to put the test file inside, e.g., `mkdir test`
2. Execute the test with `go test -v ./test`
3. See the output is not colored
4. Now, cd into the test folder `cd test`
5. Execute the test with `go test -v`
6. See the colored output

**Source Code**
```go
package test

import (
	"fmt"
	"testing"

	"github.com/charmbracelet/lipgloss"
)

func TestFoo(t *testing.T) {
	s := lipgloss.NewStyle().Foreground(lipgloss.Color("#FF0000")).Render("Hello World")
	fmt.Println(s)
}
```

**Expected behavior**
Show a colored output when executing the test inside or outside of the folder containing the test.

**Screenshots**
Test being executed outside of the folder cotaining the test file, notice that the output is not colored.
![image](https://github.com/charmbracelet/lipgloss/assets/20308796/5a38babc-b320-4448-a680-f48c7ec94bc1)

Test being executed inside of the folder containing the test file, notice the colored output.
![image](https://github.com/charmbracelet/lipgloss/assets/20308796/f9c12593-05f3-4def-807a-2dd9e92354ae)

**Comment by bashbunni** [comment]
**To fix this you can set `lipgloss.SetColorProfile(termenv.TrueColor)` at the beginning of your tests. We do that in our Glamour tests**

---

For more context: I'm not sure what's happening under the hood with Go tests that's causing this issue. I did check what terminal colour capabilities are being detected with each type of test, and the test being run in package list mode (where you provide an argument `./test` in this case) is providing different capabilities than the test being run in local directory mode (no args). 

It seems Lipgloss is not detecting a TTY, therefore it defaults to no colour. 

![image](https://github.com/charmbracelet/lipgloss/assets/15822994/fd816340-8a06-4d77-b5b4-698136f46437)

**Comment by LaBatata101** [comment]
Thanks!
