### ISSUE TITLE
Strange border

### ISSUE THREAD

**Issue by PrinnyRay** [charmbracelet/lipgloss#30]
I found border rendering is very strange, I've tried on Windows Terminal and legacy CMD, both are missing some characters, am I missing some configs?
![7cf793398ba9c0f97cad7e956f9ccf1](https://user-images.githubusercontent.com/18678790/117253558-e7503000-ae79-11eb-97c7-4167dd9c78d3.png)
![baff54d81acc85835c65aadec4cdad6](https://user-images.githubusercontent.com/18678790/117253611-f8993c80-ae79-11eb-97f8-1051951968a2.png)
Here is my code:
`logo := "foo bar"
	fmt.Printf(lipgloss.NewStyle().BorderStyle(lipgloss.DoubleBorder()).Render(logo))`

BTW, I love this lib and bubbletea. I'm trying to build a cli tool in go, your repo is the most elegant framework I've ever seen. Thanks for building this.

**Comment by PrinnyRay** [comment]
and example code looks like this...
![8fd1cfa217d3fe449de60ebdbb8eb29](https://user-images.githubusercontent.com/18678790/117255036-bf61cc00-ae7b-11eb-99d2-15800eaadb37.png)

**Comment by meowgorithm** [comment]
Thank you for the kind words on Lip Gloss and Bubble Tea!

And oh my, this looks quite odd. We'll investigate this shortly and get back to you. Thanks for flagging this.

**Comment by meowgorithm** [comment]
Hi! I'm not able to produce this behavior on Windows (see the screenshot below showing Lip Gloss output in Windows Terminal, PowerShell standalone, and the legacy command console in Windows 10.

Are there any more details you can provide on your environment? In particular, Windows version, terminal font…and maybe locale?

<img width="1602" alt="windows" src="https://user-images.githubusercontent.com/25087/117372338-5daf5b00-ae97-11eb-95bc-a7ca7d5f32a9.png">

**Comment by PrinnyRay** [comment]
My envs are:
Windows 10 Pro for Workstations， Ver.2004 Build.19041
Windows terminal Font is Consolas 12pt and YaHei UI
Legacy CMD is SimSun（I think Western Letter fallback is Times New Roman）
And Goland IDE integrated Terminal is JetBrains Mono （with default SimSun fallback）
![de6737b09518910aa36b822f11e3eef](https://user-images.githubusercontent.com/18678790/117386755-01d9e600-af1a-11eb-86df-69b3034fba52.png)

**Comment by meowgorithm** [comment]
I think this may be a font issue…but it's difficult to say. Could you try putting this this into a text file:

```
╔═══════╗
║foo bar║
╚═══════╝
```

…and then running `type filename.txt` to print it to the console?

**Comment by PrinnyRay** [comment]
I got this。。
![96ba9e1e4b23369b9b2917a96fce297](https://user-images.githubusercontent.com/18678790/117388339-30a58b80-af1d-11eb-8560-9ce79b1b6ba6.png)
![88f38a31d5a050b757ac28f25070413](https://user-images.githubusercontent.com/18678790/117388524-7febbc00-af1d-11eb-83c3-9e36d5c7e5e8.png)

This always happens when encoding are not matching. You remind me that I'm not using unicode console, I'll check it.

**Comment by meowgorithm** [comment]
Cool, let me know! The other thing to double check is that all your fonts (including the fallbacks are monospaced fonts (and not proportional ones). In both cases it looks like your Latin fonts (and maybe your CJK ones as well) are proportional fonts.

**Comment by PrinnyRay** [comment]
Solved.
I changed the cmd encoding to utf-8 and layout looks perfect.
![5ec04b148a08ddad8ec8015f4a5ae03](https://user-images.githubusercontent.com/18678790/117390473-d7d7f200-af20-11eb-99f1-bc6de142a2f9.png)
![27a325752e0d86b646144a26ef0bc02](https://user-images.githubusercontent.com/18678790/117389693-5338a400-af1f-11eb-86c2-bec63fcb3222.png)
I guess the default charset for Windows with Simplified Chinese is GBK, and charset in windows is also called active console code page. For me it is 936 for default, that means I'm using GBK encoding.  
Use `chcp 65001` to change to utf-8 encoding according to this [page](https://en.wikipedia.org/wiki/Windows_code_page).
I think if you run `chcp 936` before you run the program, you would get the same result.

**Comment by meowgorithm** [comment]
Awesome. This is really good to know. Thanks for the details on how you fixed it.

I’m going to close this issue, but feel free to open it back up if you notice any other odd behavior.

**Comment by yechentide** [comment]
I have a same problem on MacOS.

Terminal: iTerm
font: MesloLGS NF
SHELL: zsh 5.8 (x86_64-apple-darwin21.0)
theme: powerlevel10k
character encoding: Unicode(UTF-8)
terminal type: xterm-256color

I tried pasting this string into a text file, and use `cat filename.txt` to get output, it is ok.
```
╔═══════╗
║foo bar║
╚═══════╝
```

Here is my test code:
```go
var style = lipgloss.NewStyle().
	BorderStyle(lipgloss.NormalBorder()).
	BorderForeground(lipgloss.Color("63"))

func main() {
	fmt.Println(style.Render("Hello lipgloss!"))
}
```
output:
```
┌────────┐
│Hello lipgloss!│
└────────┘
```
