### ISSUE TITLE
How to create trees

### ISSUE THREAD

**Issue by hanxuanliang** [charmbracelet/lipgloss#312]
**Describe the bug**

Upon reviewing the current release, the utilization of the tree has been eliminated. Now, what is the optimal approach for utilizing the tree API?

**Comment by carreter** [comment]
For anyone who is having issues with importing the `tree` and `list` modules, you can tell go to use the master branch release instead of the latest release:

```go get github.com/charmbracelet/lipgloss@master```

**Comment by meowgorithm** [comment]
As a note, tree and list are in master but not considered yet finalized until release, and we do expect to change the API a little more.

**Comment by bashbunni** [comment]
Hey, just an update. We've been working on lists and trees for a while now and have decided to bring the tree package out of internal. The linked PR includes examples on usage and a section in the `README` to get started with trees. Will keep this issue open until that PR is merged :)
