### ISSUE TITLE
Explicitly setting the color profile

### ISSUE THREAD

**Issue by komalali** [charmbracelet/lipgloss#33]
Curious how y'all test the lipgloss output. I'm currently running into issues where the terminal colors are sometimes rendered in tests and sometimes they are not, and it seems to be based on which directory I'm running `go test` from. Any ideas on how to handle this?

<img width="950" alt="Screen Shot 2021-05-26 at 10 16 31 AM" src="https://user-images.githubusercontent.com/24326455/119703506-74e4c700-be0b-11eb-9f15-dd726e347ba9.png">

**Comment by muesli** [comment]
It depends whether the string's contents get escaped or not: `\x1b...` is the escaped version of the string, so it doesn't get interpreted by the terminal. You could `strings.ReplaceAll` that byte sequence to something more human-readable like `ESC`.

**Comment by komalali** [comment]
Sweet, that should keep things consistent at least. Thanks!

**Comment by komalali** [comment]
Hmm... actually that doesn't seem to help. Even with the escape I still get different results for the string output depending on which directory I run `go test` from.

**Comment by komalali** [comment]
The function seems to return a different string based on where `go test` is run from. I'm totally stumped on how this could be happening. It does seem to respect the italics styling regardless of the directory of execution, but the lipgloss output string has none of the colors if I execute `go test ./display` but the colors are present in the string if I execute `go test` from the `display` directory.

<img width="1730" alt="Screen Shot 2021-05-26 at 11 15 36 AM" src="https://user-images.githubusercontent.com/24326455/119710939-ce50f400-be13-11eb-87e0-6f7bfa1ce024.png">

**Comment by komalali** [comment]
Ah interesting, if I execute `go test .` instead of just `go test` from the `display` directory I get the same result as running `go test ./display` from the parent directory

**Comment by meowgorithm** [comment]
@komalali Can you provide any sort of sample code to replicate the issue?

**Comment by komalali** [comment]
Indeed! Here's a minimum repro:


### Code
repro.go
```go
package main

import (
	"fmt"
	"github.com/charmbracelet/lipgloss"
)

var myStyle = lipgloss.NewStyle().Italic(true).Foreground(lipgloss.Color("205"))

func colorString(str string) string {
	return myStyle.Render(str)
}

func main() {
	fmt.Println(colorString("hello world"))
}
```

repro_test.go
```go
package main

import (
	"strings"
	"testing"
)

func Test_colorString(t *testing.T) {
	tests := []struct {
		input string
		want string
	}{
		{ "hello world", "ESC[3;38;5;205mhello worldESC[0m"},
	}
		for _, tt := range tests {
		t.Run(tt.input, func(t *testing.T) {
			got := colorString(tt.input)
			if got = strings.ReplaceAll(got, "\x1b", "ESC"); got != tt.want {
				t.Errorf("colorString() = %v, want %v", got, tt.want)
			}
		})
	}
}
```

### Instructions
1. Run `go test` - observe success
```
❯ go test  
PASS
ok      lipgloss-repro  0.164s
```
2. Run `go test .` - observe failure
```
❯ go test .
--- FAIL: Test_colorString (0.00s)
    --- FAIL: Test_colorString/hello_world (0.00s)
        repro_test.go:20: colorString() = ESC[3;mhello worldESC[0m, want ESC[3;38;5;205mhello worldESC[0m
FAIL
FAIL    lipgloss-repro  0.334s
FAIL
```

**Comment by meowgorithm** [comment]
How very odd this is. I'm seeing the same results but am quite baffled as to why they're occuring.

@muesli: note that I'm able to replicate the exact same behavior in [termenv](https://github.com/muesli/termenv) as well.

**Comment by muesli** [comment]
This is because the test outputs for entire packages get redirected, and aren't printing to stdout directly anymore. As such termenv detects that it's not rendering to a terminal and `ColorProfile` returns `Ascii` instead of an `ANSI` profile. As far as termenv is concerned, I would recommend simply using `termenv.TrueColor` as the color profile for your tests.

We will probably have to enhance lipgloss's API to enforce using different color profiles for such use-cases.

**Comment by meowgorithm** [comment]
That totally makes sense, and is easy enough to do.

**Comment by meowgorithm** [comment]
This is now in `master` and will be included in the next release.

@komalali, there's a [test](https://github.com/charmbracelet/lipgloss/blob/master/color_test.go) included which illustrates how you can use `lipgloss.SetColorProfile` in your own tests.

**Comment by komalali** [comment]
Awesome! Thanks for the quick response/turnaround.
