### ISSUE TITLE
Mixed up use of Top/Left Bottom/Right in JoinHorizontal and JoinVertical calls

### ISSUE THREAD

**Issue by shaunco** [charmbracelet/lipgloss#334]
These `JoinHorizontal` calls should use `lipgloss.Top` or `lipgloss.Bottom` rather than `lipgloss.Left` or `lipgloss.Right`:
- https://github.com/charmbracelet/lipgloss/blob/87dd58def709590a169ba141d22ab1c76081275e/internal/tree/renderer.go#L100

These `JoinVertical` calls should use `lipgloss.Left` or `lipgloss.Right` rather than `lipgloss.Top` or `lipgloss.Bottom`:
- https://github.com/charmbracelet/lipgloss/blob/87dd58def709590a169ba141d22ab1c76081275e/internal/tree/renderer.go#L84
- https://github.com/charmbracelet/lipgloss/blob/87dd58def709590a169ba141d22ab1c76081275e/internal/tree/renderer.go#L91
- https://github.com/charmbracelet/lipgloss/blob/87dd58def709590a169ba141d22ab1c76081275e/internal/tree/renderer.go#L129

**Comment by bashbunni** [comment]
Thank you! This is fixed in #342 will link this issue to that PR so it'll close once merged :)
