### ISSUE TITLE
table issue with ClearRows(), nils the data and does not reinitialize it

### ISSUE THREAD

**Issue by pachecot** [charmbracelet/lipgloss#376]
```
// this does not work...
table.ClearRows()

// data is now nil so this will not work.
table.Row("A","B","C") 
```

Here is a fix
```
// ClearRows clears the table rows.
func (t *Table) ClearRows() *Table {
	t.data = nil
	t.data = NewStringData()  /// <-- missing reinitialization.
	return t
}
```

**Comment by bashbunni** [comment]
Hey @pachecot thanks for reporting this! I encountered the same issue last week and have since made a PR to fix it. https://github.com/charmbracelet/lipgloss/pull/372

If you're able to check out that branch and see that it works for you too, it would be very much appreciated!

**Comment by pachecot** [comment]
tested it. 
looks good to me.

**Comment by bashbunni** [comment]
Thanks for doing that!
