### ISSUE TITLE
table examples panic

### ISSUE THREAD

**Issue by blacktop** [charmbracelet/lipgloss#385]
**Describe the bug**
```
❯ go run languages/main.go 
%!v(PANIC=String method: runtime error: index out of range [-2])
❯ go run mindy/main.go 
%!v(PANIC=String method: runtime error: index out of range [-1])
❯ go run pokemon/main.go
%!v(PANIC=String method: runtime error: index out of range [-2])
```
**Setup**
Please complete the following information along with version numbers, if applicable.
 - OS macOS 15.1
 - Shell [e.g. zsh, fish] fish
 - Terminal Emulator [e.g. kitty, iterm] vscode
 - Terminal Multiplexer [e.g. tmux]
 - Locale [e.g. en_US.UTF-8, zh_CN.UTF-8, etc.]

**To Reproduce**
cd examples
go mod init
run

**Additional context**
❯ go version 
go version go1.23.2 darwin/arm64

**Comment by bashbunni** [comment]
Hi @blacktop what version of lipgloss are you using?

You shouldn't need to run `go mod init` as examples already has a `go.mod` file. I'm not able to reproduce this on `master`, but would love to get to the bottom of it! Let me know what branch or version you're using and I'll try to reproduce on my machine :)

**Comment by james-maloney** [comment]
This looks to be caused by `row` being -1 indicating the header, Looks like the addition of `HeaderRow int = -1` caused this break

**Comment by blacktop** [comment]
i believe I downloaded the zip from GH (didn't clone) so it would've been master at the time I created this issue

**Comment by blacktop** [comment]
I just tried again, downloaded zip

cd examples
```bash
❯ go run table/languages/main.go 
%!v(PANIC=String method: runtime error: index out of range [-2])
```

**Comment by blacktop** [comment]
It looks like @james-maloney hit the nail on the head, I'm confused as to how you weren't able to recreate though 😕

**Comment by bashbunni** [comment]
Ah good point. Funny, I remember updating those examples, but must've not pushed those changes to the PR where I added `HeaderRow` 🤔 Thanks for reporting! Will update them accordingly

**Comment by bashbunni** [comment]
Hey, just merged a fix for this. Please ping me if this is still an issue on your end :)

**Comment by blacktop** [comment]
Thanks Bash!
