### ISSUE TITLE
[Question] How to force text to wrap?

### ISSUE THREAD

**Issue by mritd** [charmbracelet/lipgloss#43]
I created a UI with only 64 width, but if the text contains "file path", the text will not be forced to wrap:

**The text contains "file path":**

![image](https://user-images.githubusercontent.com/13043245/131981515-5df8d0ac-d8ec-4bd3-88f3-680d744fafc6.png)

**The text does not contain "file path":**

![image](https://user-images.githubusercontent.com/13043245/131981846-8b285c5b-24d7-4041-889c-2ba6f675d688.png)

**Comment by meowgorithm** [comment]
Hey, @mritd! We’ve seen this come up a few times, so we've updated Lip Gloss to force-wrap long strings as a default behavior. This is now in `master` and will be included in the next release. In the meantime you can pin to `master` to get this functionality immediately:

```
go get github.com/charmbracelet/lipgloss@master
```

**Comment by meowgorithm** [comment]
This is now available in release `v0.4.0`.

**Comment by meowgorithm** [comment]
@espcaa use [`ansi.Truncate`](https://pkg.go.dev/github.com/charmbracelet/x/ansi#Truncate)
