### ISSUE TITLE
Colors not working

### ISSUE THREAD

**Issue by kjell0w** [charmbracelet/lipgloss#82]
Hey, somehow colors are not working for me.

**What i did**
Clone this Repo, cd into examples and ran `go mod tidy` to download deps.

**What did i expect**
See the exact same UI as in this Repos Readme. Sadly colors are not working for me
![image](https://user-images.githubusercontent.com/55231995/164763842-def448d0-5d22-4a92-803c-94cb48a0cc2d.png)

My Terminal supports 256 colors, so this should not be the problem.
![image](https://user-images.githubusercontent.com/55231995/164764096-95f7fef8-947d-404e-9c72-bdf35c7de059.png)

Do you have any ideas what could cause this issue?

Best regards

**Comment by muesli** [comment]
It looks like it's not properly detecting your terminal. Which one do you use and what are the settings of the `TERM` and `COLORTERM` environment variables?

**Comment by kjell0w** [comment]
Im using st (simple-terminal) from suckless. `TERM` env var is set to st, `COLORTERM` is unset. Tried setting `COLORTERM` to st, but that didn't change anything

**Comment by muesli** [comment]
Try setting `COLORTERM` to `yes` or `true` (either should work) for ANSI256 color output.

**Comment by kjell0w** [comment]
Thanks, now its working!
