### ISSUE TITLE
weird wordwrapping

### ISSUE THREAD

**Issue by jon4hz** [charmbracelet/lipgloss#88]
Hi, I'm facing some weird behavior when I use lipgloss to wrap some strings. Somehow it doesn't behave the same way as `wrap.String()` from @muesli's `reflow` package. 

### Example
```go
package main

import (
	"fmt"

	"github.com/charmbracelet/lipgloss"
	"github.com/muesli/reflow/wrap"
)

var x = "x10-test, x10-ab, x10-test1, x10-test10-test, x10-testing-this"

func main() {
	fmt.Println(wrap.String(x, 28))
	fmt.Println(lipgloss.NewStyle().Width(28).Render(x))
}
```

### Result
Using `wrap.String()` prints:
```
x10-test, x10-ab, x10-test1,
x10-test10-test, x10-testing
-this
```

Using `lipgloss`:
```
x10-test, x10-ab, x10-test1,
x10-test10-test, x10-testing
-
this
```

Is there an option I'm missing in lipgloss or am I wrong to expect them to behave the same?

**Comment by meowgorithm** [comment]
Hey, @jon4hz! It's actually this bug in `reflow` upstream: https://github.com/muesli/reflow/issues/43.

**Comment by jon4hz** [comment]
Hmm I see, thanks for the clarification. I guess as a workaround I can wrap the string using `reflow` and not applying a width at all for my use case :)

**Comment by muesli** [comment]
Apologies for this being such a long-standing bug. There's a PR with a fix I'm working on.

**Comment by jon4hz** [comment]
Hey :) 

Is there any update on this?

**Comment by bashbunni** [comment]
Hey @jon4hz this is fixed on `master`. We're now using [`x/ansi`](https://github.com/charmbracelet/x/blob/main/ansi/wrap.go) which will word wrap and hard wrap lines of a given width. I'm going to close this issue. Please let us know if you run into anything else!
